### ISSUE TITLE
Bitdefender moved to quarantine

### ISSUE THREAD

**Issue by sslesar** [goaaats/FFXIVQuickLauncher#32] opened 2019-05-30 17:04 UTC
Why you made a malicious behaviour after new update launcher? There screenshots:

![image](https://user-images.githubusercontent.com/25612653/58649909-4b206480-8305-11e9-91a3-d74c2dfb34fc.png)

**Comment by goaaats** [comment] 2019-05-30 17:45
BitDefender seems to overreact a bit it seems, this is for the new chat features. It injects itself into the game, that's why it seems to detect them as malicious.
I'm not quite sure what you have it set to, here are VirusTotal reports of current versions and they all seem to scan fine? Even BitDefender shows it as clean.

https://www.virustotal.com/de/file/54fa718c7d68549746dd8ad343fcd42e7e623183ec77a635b6f2bdc4ddd12a92/analysis/1559238043/ 
https://www.virustotal.com/de/file/4769d17eaca8f1584b145146750662c9ff7913fecaa617ba4dbdf95a49c38ac7/analysis/1559238043/
https://www.virustotal.com/de/file/bb8a2047a8f15302271447ebc813199f55a71b15bb8f5ab91731e34b9d15de1b/analysis/1559238270/

**Comment by sslesar** [comment] 2019-05-30 18:05
Very strange, When I open launcher and was pop up about can't update latest laucher while I lost connection to the internet. So I waste 1 hour to solve my ISP and was faulty 1.1.1.1 DNS, so I did my ISP DNS and working internet. Now on my desktop has gone launcher.
So I think it was error launcher when no internet or bad connection then appear hooks something.

**Comment by goaaats** [comment] 2019-12-07 18:55
AV issue, no way to fix for sure - closing as "working as intended"

**Closed by goaaats** 2019-12-07 18:55 UTC
