### ISSUE TITLE
Game launches without XIVLauncher

### ISSUE THREAD

**Issue by Mike503483** [goaaats/FFXIVQuickLauncher#159] opened 2020-02-21 13:51 UTC
Whenever I launch the game, it hangs for a moment, the game launches with none of the launcher features, and I get this error:

System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
False
False
False
English

[]

**Comment by Zyian** [comment] 2020-02-21 13:52
Duplicate of #153

**Comment by Aida-Enna** [comment] 2020-02-21 13:52
Duplicate of #153 - Square did some funky stuff we need to fix.

**Closed by Aida-Enna** 2020-02-21 13:52 UTC
