### ISSUE TITLE
Launcher recently giving me this error.

### ISSUE THREAD

**Issue by restinya** [goaaats/FFXIVQuickLauncher#104] opened 2019-10-09 20:23 UTC
Was not an issue until yesterday but it now throws this exception at me if I attempt to open a 2nd client.

System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, Boolean closeMutants) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 211
3.6.0.0
3051009
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
False
False
False
English

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": false,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]

**Comment by pigsflew** [comment] 2019-10-11 08:39
That's the launcher reacting to the game closing unexpectedly--it doesn't look like the launcher is causing an error here, it looks like the game client's second instance is failing to launch appropriately.

Specifically, [this log line is here](https://github.com/goaaats/FFXIVQuickLauncher/blob/305100903cdd7b9a565633df8f6b6a44b221267b/XIVLauncher/Game/XivGame.cs#L202); I'm unsure how it got line 211, since it should have thrown at line 202...

**Comment by Aida-Enna** [comment] 2020-02-21 12:00
@restinya Is this still an issue?

**Comment by Aida-Enna** [comment] 2020-02-22 12:25
Tested, and unable to reproduce with the current version. Assuming fixed. Please re-open an issue if it's not working on the latest client (after it's fixed for 5.2!). Thank you!

**Closed by Aida-Enna** 2020-02-22 12:25 UTC
