### ISSUE TITLE
OTP window failing

### ISSUE THREAD

**Issue by LunarGaze** [goaaats/FFXIVQuickLauncher#94] opened 2019-09-11 01:16 UTC
For some reason the window to enter the OTP doesn't show and then closes.
https://imgur.com/a/rH0cYCd

I just updated Windows 10 with the following updates:
https://imgur.com/7lWLfag

I'm not sure what can be done. I've tried redownloading the quicklauncher but that doesn't seem to fix anything.

**Comment by mmaine** [comment] 2019-09-11 22:09
Same issue. After last update, OTP window just doesn't even exist. With OTP+Autologin, Launcher opens and closes and shift+admin it'll just close launcher upon hitting the login key.

output.log has nothing useful:
`2019-09-12 01:08:15.908 +03:00 [INF] XIVLauncher started as xivlauncher-3.6.0.0-3051009
2019-09-12 01:08:15.977 +03:00 [INF] Loaded UI theme resource.
2019-09-12 01:08:15.979 +03:00 [INF] Loading MainWindow for account ''
2019-09-12 01:08:16.341 +03:00 [INF] Starting update check.
2019-09-12 01:08:16.472 +03:00 [INF] AutoUpdaterOnCheckForUpdateEvent called.
2019-09-12 01:08:16.475 +03:00 [INF] No update: 3.6.0.0
2019-09-12 01:08:18.062 +03:00 [INF] MainWindow initialized.
2019-09-12 01:08:33.374 +03:00 [INF] XIVLauncher started as xivlauncher-3.6.0.0-3051009
2019-09-12 01:08:33.441 +03:00 [INF] Loaded UI theme resource.
2019-09-12 01:08:33.444 +03:00 [INF] Loading MainWindow for account ''
2019-09-12 01:08:33.813 +03:00 [INF] Starting update check.
2019-09-12 01:08:33.939 +03:00 [INF] AutoUpdaterOnCheckForUpdateEvent called.
2019-09-12 01:08:33.942 +03:00 [INF] No update: 3.6.0.0
2019-09-12 01:08:35.428 +03:00 [INF] MainWindow initialized.
`

**Comment by mmaine** [comment] 2019-09-15 07:14
Update: If one runs RTSS (RivaTuner Statistics Server) that's the cause. Another software had this issue, and upon disabling RivaTuner the problem disappeared and launcher now starts. Something something d3d9.dll failing and set to software rendering mode. Started happening in latest windows update.

**Comment by goaaats** [comment] 2019-09-15 07:17
Thank you very much for looking into this. I tried to figure this out, but couldn't find any cause - I'll blame it onto WPF and add a flag to disable hardware rendering.

**Comment by mmaine** [comment] 2019-09-15 07:50
All credit goes to Leonblade. I got this info from him!

**Comment by cidrei** [comment] 2019-09-17 20:17
You can also continue to use both RTSS and the launcher by[ resetting the cache](https://i.imgur.com/j2xDf5q.png) in the RTSS settings. This seems to fix a lot of issues with RTSS and other programs lately.

**Comment by goaaats** [comment] 2019-12-07 18:48
This was related to an issue with RivaTuner, which should be fixed now as soon as you update it. Thanks everyone!

**Closed by goaaats** 2019-12-07 18:48 UTC
Labels: bug
