### ISSUE TITLE
Launcher lingers in the background

### ISSUE THREAD

**Issue by tmprnc** [goaaats/FFXIVQuickLauncher#172] opened 2020-02-25 23:20 UTC
The launcher starts as normal and manages to launch the game, but the launcher then remains in the background. If the game is launched in silent mode with the launcher not appearing, its .exe remains in the list of processes after the game has launched, and even long after it has closed. If the game was not launched in silent mode, and there was a window, it will also remain, but it is impossible to interact with and does not respond (though, not in the Windows sense, as it does not report as such) and you cannot move it around on the desktop, you cannot click any UI element. It still appears as a window in alt-tab view but otherwise acts like a frozen picture.

This is not really a problematic issue, but I thought I'd report it nonetheless.

Here's what output.log says:

> 2020-02-25 22:43:57.267 +01:00 [INF] XIVLauncher started as xivlauncher-4.7.2.0-65be2ff
> 2020-02-25 22:43:57.364 +01:00 [INF] Loaded UI theme resource.
> 2020-02-25 22:43:57.368 +01:00 [INF] Loading MainWindow for account ''
> 2020-02-25 22:44:34.655 +01:00 [INF] MainWindow initialized.
> 2020-02-25 22:44:48.483 +01:00 [INF] StartGame() called
> 2020-02-25 22:44:48.739 +01:00 [INF] XivGame::Login(steamServiceAccount:True, cache:False)
> 2020-02-25 22:44:48.739 +01:00 [INF] Cache is invalid or disabled, logging in normally.
> 2020-02-25 22:44:50.304 +01:00 [INF] OAuth login successful - playable:True terms:True region:3 expack:3
> 2020-02-25 22:44:51.799 +01:00 [INF] XivGame::LaunchGame(steamIntegration:True, steamServiceAccount:True, args:)
> 2020-02-25 22:47:34.278 +01:00 [INF] XIVLauncher started as xivlauncher-4.7.2.0-65be2ff
> 2020-02-25 22:47:34.387 +01:00 [INF] Loaded UI theme resource.
> 2020-02-25 22:47:34.391 +01:00 [INF] Loading MainWindow for account ''
> 2020-02-25 22:47:36.055 +01:00 [INF] Engaging Autologin...
> 2020-02-25 22:47:36.066 +01:00 [INF] StartGame() called
> 2020-02-25 22:47:36.321 +01:00 [INF] XivGame::Login(steamServiceAccount:True, cache:False)
> 2020-02-25 22:47:36.321 +01:00 [INF] Cache is invalid or disabled, logging in normally.
> 2020-02-25 22:47:37.897 +01:00 [INF] OAuth login successful - playable:True terms:True region:3 expack:3
> 2020-02-25 22:47:39.436 +01:00 [INF] XivGame::LaunchGame(steamIntegration:True, steamServiceAccount:True, args:)
> 2020-02-26 00:05:55.074 +01:00 [INF] XIVLauncher started as xivlauncher-4.7.2.0-65be2ff
> 2020-02-26 00:05:55.320 +01:00 [INF] Loaded UI theme resource.
> 2020-02-26 00:05:55.327 +01:00 [INF] Loading MainWindow for account ''
> 2020-02-26 00:05:57.771 +01:00 [INF] Engaging Autologin...
> 2020-02-26 00:05:57.810 +01:00 [INF] StartGame() called
> 2020-02-26 00:05:58.072 +01:00 [INF] XivGame::Login(steamServiceAccount:True, cache:False)
> 2020-02-26 00:05:58.073 +01:00 [INF] Cache is invalid or disabled, logging in normally.
> 2020-02-26 00:05:59.667 +01:00 [INF] OAuth login successful - playable:True terms:True region:3 expack:3
> 2020-02-26 00:06:01.311 +01:00 [INF] XivGame::LaunchGame(steamIntegration:True, steamServiceAccount:True, args:)

Using FFXIV in DX11, Launcher 4.7.2.0 on Windows 10 build 19041.84, Steam service enabled — no Steam running in the background — and no plugins besides the default and Discord RPC enabled.

**Comment by goaaats** [comment] 2020-02-26 00:46
Hi, this is a feature! It needs to be in background for rich presence and to be able to close apps it started.
It shouldn't really use any resources though, hope that's fine by you :)

**Comment by tmprnc** [comment] 2020-02-26 11:35
But is the actual, _visible UI_ meant to remain as an unresponsive window? It's not really a problem since I can just crash the process, and, as you said, doesn't use system resources but I find it strange it behaves this way.

**Comment by Aida-Enna** [comment] 2020-02-26 16:38
Unintended behavior, marked as bug. If anyone else has this issue, please comment with detailed info (if possible). Thank you!

**Comment by Aida-Enna** [comment] 2020-03-04 12:38
@tmprnc Can you confirm that this is still happening on the latest version?

**Comment by tmprnc** [comment] 2020-03-04 20:29
This no longer happens.

Although I have not started the game yet today, there were other "error" messages claiming that the game fails to launch while the game launched just fine, but the launcher behaved perfectly as intended (it remains not because it's frozen but because it believes there's an error message deserving of my attention) and the window was perfectly responsive, This is irrelevant to this issue, since I'm sure you've been well aware of it and that this has been a thing since 5.2.

**Closed** 2020-03-04 20:31 UTC
Labels: bug, needs to be investigated
