### ISSUE TITLE
Error when starting the game

### ISSUE THREAD

**Issue by gipsem** [goaaats/FFXIVQuickLauncher#165] opened 2020-02-22 11:54 UTC
System.Exception: Game exited prematurely
   à XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) dans D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:ligne 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
True
True
French

[]

**Comment by Aida-Enna** [comment] 2020-02-22 12:15
Duplicate of #153

**Closed by Aida-Enna** 2020-02-22 12:15 UTC
