### ISSUE TITLE
Downloaded Latest Setup and getting below error

### ISSUE THREAD

**Issue by laelipoo** [goaaats/FFXIVQuickLauncher#154] opened 2020-02-19 23:02 UTC
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
True
True
English

[]

**Comment by katawajojo** [comment] 2020-02-19 23:07
Duplicate of https://github.com/goaaats/FFXIVQuickLauncher/issues/153

**Comment by katawajojo** [comment] 2020-02-19 23:07
This is due to Anti-modding measures by Squenix. It's currently being worked on.

**Closed** 2020-02-20 05:18 UTC
