### ISSUE TITLE
Need Help with Error

### ISSUE THREAD

**Issue by mattarolla** [goaaats/FFXIVQuickLauncher#163] opened 2020-02-21 20:00 UTC
`System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
False
False
English

[]`

It says something about Steam so FYI I am not running the Steam version and I do not have that checked off in the settings. Also, the client launches fine so I don't know why it's saying it closed unexpectedly.

**Comment by Zyian** [comment] 2020-02-21 20:02
Duplicate of #153

**Comment by hmm-norah** [comment] 2020-02-21 20:25
As a side note, the variables you see that mention  Steam have a true/false value because it’s a boolean. Since you aren’t using Steam, the variables are false and don’t come in to play with this error.

**Closed** 2020-02-22 01:14 UTC
