### ISSUE TITLE
Launches fine with 'System.Exception: Game exited prematurely' error

### ISSUE THREAD

**Issue by zerodivisionerr** [goaaats/FFXIVQuickLauncher#155] opened 2020-02-20 01:34 UTC
Launcher works fine (much thanks for all the work. I love it), but also pops up the error message below.

Expected results: Launches without any additional errors

Actual results: Launches and also opens an error box with the following;
```
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
True
True
English


[]
```

**Comment by ackwell** [comment] 2020-02-20 01:36
duplicate of #153 
there's been some new crap from SE that needs to be worked around.

**Closed** 2020-02-20 05:16 UTC
