### ISSUE TITLE
Error when launching with quick launcher

### ISSUE THREAD

**Issue by atomkats** [goaaats/FFXIVQuickLauncher#158] opened 2020-02-21 00:42 UTC
Sorry I don't know much about coding haha. But ever since the 5.2 update I've been getting this error when launching the game via the quick launcher. The game itself starts fine, but the error pops up each time I launch.

System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
True
True
English

[]

**Comment by Amenne-ennemA** [comment] 2020-02-21 00:52
Duplicate of #153 This is due to Anti-modding measures by Squenix. It's currently being worked on.

**Closed** 2020-02-21 01:01 UTC
