### ISSUE TITLE
Game crashes on closing

### ISSUE THREAD

**Issue by NNowakowski** [goaaats/FFXIVQuickLauncher#206] opened 2020-03-31 19:48 UTC
**Describe the bug here:**
The latest launcher update caused my game to crash whenever I try to exit the game in the menu. I'm using the new Discord rich presence plugin aswell.

**Steps to reproduce the bug:**
1. Install the latest version of the launcher
2. Install and enable the Discord Rich Presence plugin
3. Exit the game

**Expected behavior**
No crash on exit

**Screenshots**
![image](https://user-images.githubusercontent.com/16933892/78068532-d987cb80-7398-11ea-929b-76267e1be4fc.png)

**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: 4.8.2
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: Discord Rich Presence

**Additional information**
-/-

**Comment by goaaats** [comment] 2020-03-31 19:48
This is a duplicate of a Dalamud issue, we're working on it! Hope we can resolve it soon, thanks for reporting.

**Closed by goaaats** 2020-03-31 19:48 UTC
