### ISSUE TITLE
Cant really launch the launcher which worked literally a day ago or download the setup.exe

### ISSUE THREAD

**Issue by markynatorka** [goaaats/FFXIVQuickLauncher#135] opened 2020-01-01 10:35 UTC
![image](https://user-images.githubusercontent.com/42062385/71640464-be6aca00-2c8a-11ea-9e96-1c2a5cc54e66.png)

**Comment by twocows** [comment] 2020-01-01 11:06
I also get this.

![Capture](https://user-images.githubusercontent.com/6536741/71640689-cad82e00-2c5c-11ea-8d2c-2dc3787dceb4.PNG)

**Comment by goaaats** [comment] 2020-01-01 11:07
I assume this is an issue with Windows 7. I'll try to fix it, but I have no way to test it and Windows 7 is EoL in 2 weeks so I'm probably not gonna do any more compatibility stuff for it after making this work again, sorry!

**Comment by twocows** [comment] 2020-01-01 11:12
I can send you a small-ish test VM or something if you want

**Comment by goaaats** [comment] 2020-01-01 11:13
If you can reproduce it there, that would be great - discord is goat#3048

**Comment by Aida-Enna** [comment] 2020-02-21 12:25
@twocows Is this still an issue?

**Comment by twocows** [comment] 2020-02-21 22:53
Nope. I'm getting this, but the game launches successfully so it's not really a problem.
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230

**Comment by Aida-Enna** [comment] 2020-02-21 22:54
Ah, that's issue #153. Closing since this one is resolved.

**Closed by Aida-Enna** 2020-02-21 22:54 UTC
