### ISSUE TITLE
Recent Error with new FFXIV Patch

### ISSUE THREAD

**Issue by briankurtz249** [goaaats/FFXIVQuickLauncher#156] opened 2020-02-20 05:08 UTC
Funnily enough, the program still "functions" as in logging me in and launching the game, but will then spit out this error message. Thought maybe you'd have some use for it?

-------------------------------------------------------------------------------------------------------

System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
True
True
English

[]

**Comment by goaaats** [comment] 2020-02-20 05:17
duplicate of #153
some new stuff from SE we need to work around

**Closed by goaaats** 2020-02-20 05:17 UTC
