### ISSUE TITLE
game exited when launching dualbox client

### ISSUE THREAD

**Issue by GaeaRW** [goaaats/FFXIVQuickLauncher#145] opened 2020-01-17 05:36 UTC
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
False
False
False
English

[]

**Comment by Aida-Enna** [comment] 2020-02-21 12:27
duplicate of #153, closing (even though you were first, sorry!)

**Closed by Aida-Enna** 2020-02-21 12:27 UTC
