### ISSUE TITLE
Launcher issue when pressing log in

### ISSUE THREAD

**Issue by TheFLAMEffect** [goaaats/FFXIVQuickLauncher#191] opened 2020-03-20 22:30 UTC
This is the first time using it, the moment i press log in i get this error.

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 246
4.7.3.0
a55b6fb
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True

[]

**Comment by karashiiro** [comment] 2020-03-20 22:36
Duplicate of #180

**Closed** 2020-03-20 22:36 UTC
