### ISSUE TITLE
Issue Opening 2nd Instance after Patch 5.18

### ISSUE THREAD

**Issue by ihaloemail** [goaaats/FFXIVQuickLauncher#127] opened 2019-12-24 17:30 UTC
Can't seem to open a 2nd instance anymore (both SE PC version under same SE account)

Error:
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, Boolean closeMutants)
4.2.0.0

**Comment by Zyian** [comment] 2019-12-25 02:33
Duplicate of #104

**Closed** 2019-12-25 02:52 UTC
